language: node_js
node_js:
  - 'node'
before_install:
- npm install -g gulp
- npm install
before_script:
- "export DISPLAY=:99.0"
- "sh -e /etc/init.d/xvfb start"
- sleep 5 # give xvfb some time to start
script:
- npm run test
